export { default as HeroSection } from './HeroSection'
export { default as FeaturesSection } from './FeaturesSection'
export { default as ProcessSection } from './ProcessSection'
export { default as PricingSection } from './PricingSection'
export { default as TestimonialsSection } from './TestimonialsSection'
export { default as FAQSection } from './FAQSection'
export { default as CTASection } from './CTASection'