name = "rapidsite"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }