name = "rapidsite"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[env.production]
vars = { ENVIRONMENT = "production" }
# Custom domains are configured via Cloudflare Dashboard
# Routes would be: rapidsite.io/* (if using zone-based routing)

[env.staging]
vars = { ENVIRONMENT = "staging" }