name = "rapidsite"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[env.production]
name = "rapidsite-production"
vars = { ENVIRONMENT = "production" }
routes = [
  { pattern = "rapidsite.io/*", zone_name = "rapidsite.io" },
  { pattern = "www.rapidsite.io/*", zone_name = "rapidsite.io" }
]

[env.staging]
vars = { ENVIRONMENT = "staging" }