name = "rapidsite"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[env.production]
vars = { ENVIRONMENT = "production" }
routes = [
  { pattern = "rapidsite.io/*", custom_domain = true }
]

[env.staging]
vars = { ENVIRONMENT = "staging" }
routes = [
  { pattern = "*.preview.rapidsite.io/*", custom_domain = true }
]