name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Run tests
        run: pnpm test -- --run
        
      - name: Build project
        run: pnpm run build
        env:
          NODE_ENV: production
          
      - name: Install Wrangler
        run: npm install -g wrangler
        
      - name: Copy built site to worker
        run: |
          mkdir -p workers/site/dist
          cp -r dist/* workers/site/dist/
          
      - name: Deploy Site Worker
        run: |
          cd workers/site
          pnpm install --no-frozen-lockfile
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            wrangler deploy --env production
          else
            wrangler deploy --env staging
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          
      - name: Comment PR
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deployment_url = `https://staging-rapidsite.nexabyte.co.uk`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployment is ready!\n\nView deployment: ${deployment_url}`
            });